"""
VLM Captioner — per-shot video caption via the OpenRouter Qwen3-VL endpoint.

Inspired by VideoRAG (per-segment MiniCPM-V) and NVIDIA VSS (per-segment
Cosmos-Reason): adding a short VLM caption per shot is the standard
substitute for an audio-only transcript when the shot has no speech.
The caption embedding (joined with the transcript) becomes the primary
text signal for retrieval of silent shots — lecture cutaways, B-roll,
animations.

We use the **same Qwen3-VL endpoint the agent's VQA tool already uses**
(``qwen/qwen3-vl-8b-instruct`` via OpenRouter, configured via
``VLM_MODEL`` / ``OPENROUTER_API_KEY``). This means:

  - No local VLM weights to download / no extra VRAM contention.
  - Captioning works identically on CPU dev, Colab T4, or any host.
  - The retrieval-time caption is generated by the *same model* the
    agent uses at query time for VQA — so the semantic signal aligns
    end-to-end.

Public API:
    cap = VLMCaptioner()
    if cap.is_available():
        captions = cap.caption_batch(frame_batches)

    # When unavailable (no OPENROUTER_API_KEY, openai SDK missing,
    # CAPTION_ENABLED=false), caption_batch returns "" per entry — the
    # ingest pipeline silently falls back to transcript-only retrieval.

``caption_shot(frames)`` and ``caption_batch(frame_batches)`` accept the
output of ``indexer.extract_frames`` directly (uint8 RGB [N, H, W, 3]).
The caller is expected to have already sampled frames for CLIP-L — we
reuse the same batch rather than re-extracting.
"""
import logging
import os
from typing import List, Optional

import numpy as np

log = logging.getLogger(__name__)


_UNAVAILABLE = "unavailable"
_DEFAULT_PROMPT = (
    "Describe what is happening in this short video clip in one or two "
    "factual sentences. Focus on visible subjects, actions, and setting. "
    "Output only the description — no prefix, no quotes, no labels."
)


def _resolve_enabled(raw: str, has_api_key: bool) -> bool:
    """Resolve CAPTION_ENABLED env value:
       ``auto`` (default) → True iff an OpenRouter API key is configured
       ``true|1|yes`` → True
       anything else → False
    """
    raw = (raw or "").strip().lower()
    if raw == "auto":
        return has_api_key
    return raw in ("true", "1", "yes")


class VLMCaptioner:
    """Per-shot video captioner via OpenRouter Qwen3-VL.

    Public API:
      - ``is_available()`` — True iff the client is configured
      - ``caption_shot(frames) -> str``
      - ``caption_batch(frame_batches) -> List[str]``

    All methods are safe to call when unavailable — they return empty
    strings rather than raising. This matches the ``WhisperASR`` pattern
    so the ingest pipeline doesn't need to special-case availability.
    """

    def __init__(
        self,
        api_key: Optional[str] = None,
        model: Optional[str] = None,
        base_url: str = "https://openrouter.ai/api/v1",
        max_new_tokens: int = 80,
        max_frames: int = 8,
        enabled: Optional[bool] = None,
        prompt: str = _DEFAULT_PROMPT,
    ):
        self.api_key = api_key if api_key is not None else os.environ.get("OPENROUTER_API_KEY", "")
        self.model = model or os.environ.get("VLM_MODEL", "qwen/qwen3-vl-8b-instruct")
        self.base_url = base_url
        self.max_new_tokens = max_new_tokens
        self.max_frames = max_frames
        self.prompt = prompt
        if enabled is None:
            enabled = _resolve_enabled(
                os.environ.get("CAPTION_ENABLED", "auto"),
                bool(self.api_key),
            )
        self.enabled = enabled

        self._client = None
        self._n_captioned = 0
        self._n_skipped = 0

    @classmethod
    def from_config(cls, config) -> "VLMCaptioner":
        """Construct from the singleton PipelineConfig."""
        return cls(
            api_key=config.openrouter_api_key,
            model=config.vlm_model,
            base_url=config.openrouter_base_url,
            max_new_tokens=getattr(config, "caption_max_new_tokens", 80),
            enabled=getattr(config, "caption_enabled", None),
        )

    # lazy loader

    def _lazy_load(self) -> None:
        if self._client is not None:
            return
        if not self.enabled:
            self._client = _UNAVAILABLE
            return
        if not self.api_key:
            log.warning(
                "VLMCaptioner: no OPENROUTER_API_KEY configured. Captioning disabled."
            )
            self._client = _UNAVAILABLE
            return
        try:
            from openai import OpenAI
            self._client = OpenAI(api_key=self.api_key, base_url=self.base_url)
            log.info(f"VLMCaptioner ready (model={self.model})")
        except ImportError:
            log.warning("openai package not installed; captioning disabled. pip install openai")
            self._client = _UNAVAILABLE

    def is_available(self) -> bool:
        """True iff caption_shot/caption_batch will produce real captions."""
        self._lazy_load()
        return self._client not in (None, _UNAVAILABLE)

    # public API

    def caption_shot(self, frames: np.ndarray) -> str:
        """Caption a single shot. ``frames`` is uint8 RGB [N, H, W, 3]."""
        self._lazy_load()
        if self._client == _UNAVAILABLE:
            self._n_skipped += 1
            return ""
        if frames is None or len(frames) == 0:
            return ""
        try:
            return self._run_one(frames)
        except Exception as e:
            log.warning(f"caption_shot failed: {e}")
            return ""

    def caption_batch(self, frame_batches: List[np.ndarray]) -> List[str]:
        """Caption N shots in parallel.

        Provider doesn't batch multi-image chat completions across separate
        conversations, so we fan out N parallel HTTP calls via a thread pool.
        Empirically this is the dominant cost of indexing on long videos:
        serial loop ≈ 1.5 s/shot × N. Parallelism collapses that to
        ceil(N / workers) × 1.5 s — ~8× faster on a 60-shot video.

        Workers default to 8 (OpenRouter handles this comfortably). Override
        with the ``CAPTION_BATCH_WORKERS`` env var.
        """
        from concurrent.futures import ThreadPoolExecutor

        self._lazy_load()
        n = len(frame_batches)
        out: List[str] = [""] * n
        if self._client == _UNAVAILABLE or n == 0:
            self._n_skipped += n
            return out

        max_workers = int(os.environ.get("CAPTION_BATCH_WORKERS", "8"))
        max_workers = max(1, min(max_workers, n))

        def _run(i: int, frames) -> tuple[int, str]:
            if frames is None or len(frames) == 0:
                return i, ""
            try:
                return i, self._run_one(frames)
            except Exception as e:  # noqa: BLE001
                log.warning(f"caption_batch item {i} failed: {e}")
                return i, ""

        with ThreadPoolExecutor(max_workers=max_workers) as pool:
            for i, caption in pool.map(lambda iv: _run(*iv), enumerate(frame_batches)):
                out[i] = caption
        return out

    # internals

    def _run_one(self, frames: np.ndarray) -> str:
        """Single VLM call over a shot's frames. Returns trimmed caption."""
        # Reuse the base64 encoder already used by VideoQA so resize / quality
        # behavior stays consistent across captioning and VQA.
        from main.encoders.video_qa import _frames_to_base64_images

        b64_images = _frames_to_base64_images(frames, max_images=self.max_frames)
        if not b64_images:
            return ""

        content = []
        for b64 in b64_images:
            content.append({
                "type": "image_url",
                "image_url": {"url": f"data:image/jpeg;base64,{b64}"},
            })
        content.append({"type": "text", "text": self.prompt})

        response = self._client.chat.completions.create(
            model=self.model,
            messages=[{"role": "user", "content": content}],
            max_tokens=self.max_new_tokens,
        )
        caption = (response.choices[0].message.content or "").strip()
        # Some providers wrap the response in quotes despite the prompt;
        # trim a leading/trailing pair if present.
        if len(caption) >= 2 and caption[0] in ('"', "'") and caption[-1] == caption[0]:
            caption = caption[1:-1].strip()
        self._n_captioned += 1
        return caption

    def stats(self) -> dict:
        return {
            "captioned": self._n_captioned,
            "skipped": self._n_skipped,
            "total": self._n_captioned + self._n_skipped,
        }


# Process-singleton convenience for the ingest pipeline.

_singleton: Optional[VLMCaptioner] = None


def _get_singleton() -> VLMCaptioner:
    global _singleton
    if _singleton is None:
        try:
            from main.encoders.config import config
            _singleton = VLMCaptioner.from_config(config)
        except Exception:
            _singleton = VLMCaptioner()
    return _singleton


def caption_shot(frames: np.ndarray) -> str:
    """Module-level convenience: caption a single shot via the singleton."""
    try:
        return _get_singleton().caption_shot(frames)
    except Exception as exc:
        log.warning("caption_shot failed (%s); returning empty", exc)
        return ""


def caption_batch(frame_batches: List[np.ndarray]) -> List[str]:
    """Module-level convenience: caption N shots via the singleton."""
    try:
        return _get_singleton().caption_batch(frame_batches)
    except Exception as exc:
        log.warning("caption_batch failed (%s); returning empty", exc)
        return ["" for _ in frame_batches]
